name: loomopro
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^4.20.0
  firebase_database: ^10.5.7
  firebase_core: ^2.32.0
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  firebase_storage: ^11.7.7
  url_launcher: ^6.3.0
  record: ^6.0.0
  google_generative_ai: ^0.4.3
  path_provider: ^2.1.3
  audioplayers: ^6.0.0
  razorpay_flutter: ^1.4.0
  video_player: ^2.10.0
  uuid: ^4.4.0
  fluttertoast: 8.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
