// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3ROMBHL8E3qAXelMs1Y1I_rqvxIDpNPk',
    appId: '1:972831421131:web:391e545baa47c124cce14e',
    messagingSenderId: '972831421131',
    projectId: 'loomo-4cf9d',
    authDomain: 'loomo-4cf9d.firebaseapp.com',
    storageBucket: 'loomo-4cf9d.firebasestorage.app',
    measurementId: 'G-Z2ZYGS08SK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgcivDut5B4VlaexcU5TLQH2DL26B3SsA',
    appId: '1:972831421131:android:3dca5f1665d8d4b5cce14e',
    messagingSenderId: '972831421131',
    projectId: 'loomo-4cf9d',
    storageBucket: 'loomo-4cf9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXs3wMPNiIfwZQF1D85dcfe9vlqVuh2cU',
    appId: '1:972831421131:ios:af7c16fbe35577d9cce14e',
    messagingSenderId: '972831421131',
    projectId: 'loomo-4cf9d',
    storageBucket: 'loomo-4cf9d.firebasestorage.app',
    iosBundleId: 'com.example.loomopro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXs3wMPNiIfwZQF1D85dcfe9vlqVuh2cU',
    appId: '1:972831421131:ios:af7c16fbe35577d9cce14e',
    messagingSenderId: '972831421131',
    projectId: 'loomo-4cf9d',
    storageBucket: 'loomo-4cf9d.firebasestorage.app',
    iosBundleId: 'com.example.loomopro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3ROMBHL8E3qAXelMs1Y1I_rqvxIDpNPk',
    appId: '1:972831421131:web:690d2a0b05307706cce14e',
    messagingSenderId: '972831421131',
    projectId: 'loomo-4cf9d',
    authDomain: 'loomo-4cf9d.firebaseapp.com',
    storageBucket: 'loomo-4cf9d.firebasestorage.app',
    measurementId: 'G-8P4BR3KPWS',
  );

}